
import pyttsx3
import time
engine = pyttsx3.init(driverName='nsss')
engine.setProperty('voice', 'com.apple.voice.compact.th-TH.Kanya')
def start():
    engine.say('ทุกคนหลับตา')
    engine.runAndWait()
    time.sleep(5)
    engine.say('แม่มดลืมตา')
    engine.runAndWait()
    time.sleep(2)
    engine.say('แม่มดเลือกวางแบล็คแค็ท')
    engine.runAndWait()
    time.sleep(1)
    for i in range(15, -1, -1):  
        engine.say(str(i))
        engine.runAndWait()    
        time.sleep(0.5)
    time.sleep(2)
    engine.say('ทุกคนลืมตา')
    engine.runAndWait() 
def night():
    engine.say('ทุกคนหลับตา')
    engine.runAndWait()
    time.sleep(5)
    engine.say("แม่มดลืมตา")
    engine.runAndWait()
    time.sleep(3)
    engine.say("แม่มดเลือกฆ่า")
    engine.runAndWait()
    time.sleep(2)
    for i in range(20, -1, -1):  
        engine.say(str(i))
        engine.runAndWait()    
        time.sleep(0.5)
    time.sleep(2)
    engine.say('แม่มดหลับตา')
    engine.runAndWait()
    time.sleep(5)
    engine.say('คอนลืมตา')
    engine.runAndWait()
    time.sleep(2)
    engine.say('คอนเลือกปกป้อง')
    engine.runAndWait()
    time.sleep(1)
    for i in range(15, -1, -1):  
        engine.say(str(i))
        engine.runAndWait()    
        time.sleep(0.5)
    time.sleep(2)
    engine.say('ทุกคนลืมตา')
    engine.runAndWait()
def nightnocon():
    engine.say('ทุกคนหลับตา')
    engine.runAndWait()
    time.sleep(5)
    engine.say("แม่มดลืมตา")
    engine.runAndWait()
    time.sleep(3)
    engine.say("แม่มดเลือกฆ่า")
    engine.runAndWait()
    time.sleep(2)
    for i in range(20, -1, -1):  
        engine.say(str(i))
        engine.runAndWait()    
        time.sleep(0.5)
    time.sleep(2)
    engine.say('ทุกคนลืทตา')
    engine.runAndWait()
nightnocon()